---
- hosts: $_hostname_
  user: $_user_
  sudo: yes
  tasks:

  - name: Unarchive the zookeeper install package to remote machine
    unarchive: src=$_package_  dest=$_packageInstallPath_

  - name: Copy zookeeper zoo.cfg
    copy: src=$_confSrc_  dest=$_confTarget_

  - name: Create data dir 
    file: path=$_dataDir_  state=directory  mode=0755

  - name: Create dataLog dir
    file: path=$_dataLogDir_  state=directory  mode=0755

  - name: Copy myid file
    copy: src=$_myidSrc_  dest=$_dataDir_

  - name: Start zookeeper
    command: $_serverScript_ start