---
- hosts: $_hostname_
  user: $_user_
  sudo: yes
  tasks:

  - name: Unarchive the redis install package to remote machine
    unarchive: src=$_package_  dest=$_packageInstallPath_

  - name: Make and make install redis
    shell: cd $_makePath_ && make && make install

  - name: Copy redis conf redis.conf
    copy: src=$_confSrc_  dest=$_confTarget_

  - name: Start redis service
    shell: $_serverScript_


