---
- hosts: $_hostname_
  user: $_user_
  sudo: yes
  tasks:

  - name: Create install path
    file: path=$_jarInstallPath_  state=directory

  - name: Create log path
    file: path=$_logDir_  state=directory

  - name: Copy collection jar
    copy: src=$_jarSrc_  dest=$_jarInstallPath_

  - name: Start collection service
    shell: $_startCommand_

  - name: Copy flume conf
    copy: src=$_flumeConfSrc_   dest=$_flumeConfPath_

  - name: pause 5s for service Start
    pause:
      seconds: 3