---
- hosts: $_hostname_
  user: $_user_
  sudo: yes
  tasks:

  - name: Start flume
    shell: nohup $_flumeScript_  agent -c  $_flumeConfDir_  -f  $_flumeConfDir_/$_flumeConfName_  -n agent-1 2>&1 > /dev/null &