---
- hosts: $_hostname_
  user: $_user_
  sudo: yes
  tasks:

  - name: Unarchive the kafka install package to remote machine
    unarchive: src=$_package_  dest=$_packageInstallPath_

  - name: Copy kafka server.Properties
    copy: src=$_confSrc_  dest=$_confTarget_

  - name: Create log dir 
    file: path=$_logDir_  state=directory  mode=0755

  - name: Start kafka
    shell: nohup $_serverScript_  $_confFile_ 2>&1 > /dev/null &