---
- hosts: $_hostname_
  user: $_user_
  sudo: yes
  tasks:

  - name: Create logging root path
    file: path=$_rootLogPath_  state=directory

  - name: Copy flume conf
    copy: src=$_flumeConfSrc_   dest=$_flumeConfPath_